name: Build

on:
  push:
    tags:
      - 'v*.*.*'  # runs on version tags, e.g. v1.0.0
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-forge make
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: out/make/